### ISSUE TITLE
Stream Link

### ISSUE THREAD

**Issue by snakedm** [Fanman03/CamViewerPlus#2]
HI. How I access to stream port 6900?
http://IpAddress:6900 » returns `Cannot GET /`

I only want an direct http url to my live stream. Its possible?

**Comment by Fanman03** [comment]
Apologies for the (very) late response. 

The web UI is available on port 6980. The raw stream data from each camera is only available as a WebSocket datastream at port 6900 under the `/api/stream/<id>` path.
