### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by mygrexit** [Fanman03/CamViewerPlus#3]
Hi, is my assumption right, that your tool can also record streams or am i misinterpreting the config file?

If it's possible to record. Where would it record the file to?

Thanks for the app, looks promising. I was looking for a simple lightweight streaming solution.

**Comment by Fanman03** [comment]
Hi,

I apologize for the late response. This tool is intended for viewing livestreams of cameras only. For recording I would recommend a more complete NVR solution like [Frigate](https://github.com/blakeblackshear/frigate/).
